const CACHE='wa-ops-v3-1635';
const STATE='wa-ops-v3-state';
const STATIC=['./','./dashboard.html','./dashboard.css','./dashboard.js','./dashboard-extras.js','./dashboard-extras-core.js','./v3.css','./v3-intelligence.js','./v3-areas.js','./v3-environment.js','./v3-map-areas.js','./v3-refinements.js','./swin-focus.js','./weather-overlays.js','./wp-source-clarity.js','./manifest.webmanifest','./icon-192.svg','./icon-512.svg'];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(STATIC)).catch(()=>{}).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('wa-ops-v3-')&&k!==CACHE&&k!==STATE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==location.origin)return;e.respondWith((async()=>{try{const r=await fetch(e.request);if(r.ok){const c=await caches.open(CACHE);c.put(e.request,r.clone())}return r}catch{const c=await caches.open(CACHE);return(await c.match(e.request))||(e.request.mode==='navigate'?await c.match('./dashboard.html'):Response.error())}})())});
async function stateGet(name,fallback){try{const c=await caches.open(STATE),r=await c.match(new Request(`https://state.invalid/${name}`));return r?await r.json():fallback}catch{return fallback}}
async function stateSet(name,data){try{const c=await caches.open(STATE);await c.put(new Request(`https://state.invalid/${name}`),new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}}))}catch{}}
self.addEventListener('message',e=>{const d=e.data||{};if(d.type==='WATCH_CONFIG')e.waitUntil(stateSet('config',d.payload||{}));if(d.type==='SHOW_NOTIFICATION'){const p=d.payload||{};e.waitUntil(self.registration.showNotification(p.title||'WAOS',p.options||{}))}});
function flat(c,out=[]){if(!Array.isArray(c))return out;if(c.length>=2&&Number.isFinite(+c[0])&&Number.isFinite(+c[1])){out.push([+c[1],+c[0]]);return out}for(const x of c)flat(x,out);return out}
function point(i){if(Array.isArray(i?.point)&&Number.isFinite(+i.point[0])&&Number.isFinite(+i.point[1]))return{lat:+i.point[0],lon:+i.point[1]};let a=flat(i?.geometry?.coordinates||[]);if(!a.length){const p=Array.isArray(i?.polygons)&&i.polygons.length?i.polygons[0]:i?.polygon;if(Array.isArray(p))a=p.filter(x=>Array.isArray(x)&&Number.isFinite(+x[0])&&Number.isFinite(+x[1])).map(x=>[+x[0],+x[1]])}if(!a.length)return null;return{lat:a.reduce((s,x)=>s+x[0],0)/a.length,lon:a.reduce((s,x)=>s+x[1],0)/a.length}}
function dist(a,b){const R=6371,r=x=>x*Math.PI/180,da=r(b.lat-a.lat),dl=r(b.lon-a.lon),x=Math.sin(da/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function type(i){const s=String(i?.source||'').toLowerCase();return s.includes('western')?'wp':s.includes('emergency')?'ewa':s.includes('main roads')?'mr':'bom'}
function important(i){const t=type(i);if(t==='ewa'||t==='bom')return true;if(t==='wp')return i.outageCategory==='unplanned'||i.planned===false;if(t==='mr')return['closed','incident','signal'].includes(i.category);return false}
function label(i){const t=type(i);return t==='ewa'?'Emergency':t==='bom'?'Weather warning':t==='wp'?'Power outage':i.categoryLabel||'Road incident'}
function signature(i){return`${type(i)}:${i.id||i.rawId||i.title||'item'}${type(i)==='wp'?`|${i.estimatedRestorationTime||''}|${i.customersImpacted??''}|${i.tags||''}`:''}`}
async function watch(){const cfg=await stateGet('config',{});if(!cfg.alerts||!Array.isArray(cfg.locations)||!cfg.locations.length||!cfg.worker)return;try{const r=await fetch(`${cfg.worker}/api/feeds`,{cache:'no-store'});if(!r.ok)return;const d=await r.json(),items=[...(d.bom||[]),...(d.emergency||[]),...(d.westernPower||[]),...(d.mainRoads||[])].filter(important),old=await stateGet('seen',{}),next={};for(const loc of cfg.locations){const before=old[loc.id]||{},now={};for(const i of items){const p=point(i);if(!p)continue;const km=dist({lat:+loc.lat,lon:+loc.lon},p);if(km>Number(loc.radius||10))continue;const sig=signature(i);now[sig]=Date.now();if(Object.keys(before).length&&!before[sig])await self.registration.showNotification(`${label(i)} near ${loc.name}`,{body:`${i.title||i.affectedArea||label(i)} · ${km.toFixed(1)} km away`,tag:`waops-${loc.id}-${sig}`.slice(0,180),icon:'./icon-192.svg',badge:'./icon-192.svg',renotify:false,data:{url:'./dashboard.html'}})}next[loc.id]=now}await stateSet('seen',next)}catch{}}
self.addEventListener('periodicsync',e=>{if(e.tag==='wa-ops-watch')e.waitUntil(watch())});
self.addEventListener('sync',e=>{if(e.tag==='wa-ops-watch')e.waitUntil(watch())});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil((async()=>{const all=await clients.matchAll({type:'window',includeUncontrolled:true});for(const c of all){if('focus'in c){await c.focus();if('navigate'in c)await c.navigate('./dashboard.html');return}}if(clients.openWindow)await clients.openWindow('./dashboard.html')})())});
