(function(){
'use strict';
const A=window.WAOS4,U=A.utils,$=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)];
let incidentFilter='all',toastTimer=null;
function toast(message){const n=$('toast');if(!n)return;n.textContent=message;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),2600);}
function sourceLabel(i){return ({ewa:'Emergency WA',wp:'Western Power',bom:'BOM',mr:'Main Roads'})[U.sourceKey(i)]||'Operational';}
function itemWhen(i){const src=U.sourceKey(i);return src==='wp'?i.outageStartTime||i.timeAdded:src==='mr'?i.updatedAt||i.startTime:i.published;}
function allItems(){return [...A.state.feeds.emergency,...A.state.feeds.westernPower,...A.state.feeds.mainRoads,...A.state.feeds.bom].filter(i=>U.visibleForZone(i,A.state.settings.zone));}
function layerVisible(i){return A.state.settings.layers[U.itemLayerKey(i)]!==false;}
function filteredItems(){let items=allItems().filter(layerVisible);if(incidentFilter!=='all')items=items.filter(i=>U.sourceKey(i)===incidentFilter);return items.sort((a,b)=>U.scoreItem(b)-U.scoreItem(a)||new Date(itemWhen(b)||0)-new Date(itemWhen(a)||0));}
function renderMetrics(){const items=allItems(),priority=items.filter(i=>U.scoreItem(i)>=70),wp=items.filter(i=>U.sourceKey(i)==='wp'&&U.wpCategory(i)==='unplanned'),customers=wp.reduce((n,i)=>n+(Number(i.customersImpacted)||0),0),warnings=items.filter(i=>['ewa','bom'].includes(U.sourceKey(i))),roads=items.filter(i=>U.sourceKey(i)==='mr'&&['closed','incident','signal','detour','restriction'].includes(i.category));$('metricPriority').textContent=priority.length;$('metricPriorityNote').textContent=priority.length?'High-attention mapped items':'No high-attention items';$('metricCustomers').textContent=customers.toLocaleString('en-AU');$('metricPowerNote').textContent=`${wp.length} unplanned outage${wp.length===1?'':'s'}`;$('metricWarnings').textContent=warnings.length;$('metricWarningsNote').textContent=`${items.filter(i=>U.sourceKey(i)==='ewa').length} emergency · ${items.filter(i=>U.sourceKey(i)==='bom').length} BOM`;$('metricRoads').textContent=roads.length;$('metricRoadsNote').textContent=`${items.filter(i=>U.sourceKey(i)==='mr'&&i.category==='closed').length} closure item${items.filter(i=>U.sourceKey(i)==='mr'&&i.category==='closed').length===1?'':'s'}`;$('zoneTitle').textContent=A.ZONES[A.state.settings.zone]?.label||'SWIN';}
function cardLink(i){const src=U.sourceKey(i),url=i.link||(src==='wp'?'https://www.westernpower.com.au/faults-outages/power-outages/':src==='mr'?'https://travelmap.mainroads.wa.gov.au/Home/Map':src==='ewa'?'https://www.emergency.wa.gov.au/':'https://www.bom.gov.au/wa/warnings/');return `<a href="${U.esc(url)}" target="_blank" rel="noopener">Verify source</a>`;}
function renderIncidents(){const items=filteredItems(),list=$('incidentList');if(!items.length){list.innerHTML='<div class="empty-state">No visible operational items match this work zone, focus mode and filter.</div>';return;}list.innerHTML=items.slice(0,150).map(i=>{const score=U.scoreItem(i),cls=score>=70?'high':score>=45?'medium':'low',src=U.sourceKey(i),cat=src==='wp'?U.wpCategory(i):i.category||'';return `<article class="incident-card priority-${cls}" data-item-id="${U.esc(U.itemId(i))}"><div class="incident-top"><span class="incident-source">${U.esc(sourceLabel(i))}${cat?` · ${U.esc(cat)}`:''}</span><span class="incident-score">P${score}</span></div><h3>${U.esc(U.itemTitle(i))}</h3>${U.itemSubtitle(i)?`<p>${U.esc(U.itemSubtitle(i)).slice(0,320)}</p>`:''}<div class="incident-meta"><span>${U.esc(U.fmtTime(itemWhen(i)))}</span><span>${U.itemPoint(i)?'Mapped':'Area reference'}</span></div>${cardLink(i)}</article>`;}).join('');}
function renderFreshness(){const f=U.freshness(A.state.feeds.updatedAt),n=$('feedFreshness');n.textContent=A.state.feeds.usingCache?'LAST KNOWN':f.label;n.className=`freshness-badge ${A.state.feeds.usingCache?'stale':f.key}`;$('headerUpdated').textContent=A.state.feeds.updatedAt?`${A.state.feeds.usingCache?'Last known':'Updated'} ${U.fmtTime(A.state.feeds.updatedAt,false)}`:'Waiting for data';$('mapStatus').textContent=`${filteredItems().length} visible items · ${A.ZONES[A.state.settings.zone]?.label||'SWIN'} · ${A.MODES[A.state.settings.mode]?.label||'Priority'} mode`;}
function renderLayerCounts(){const zone=allItems();$('count-ewa').textContent=zone.filter(i=>U.sourceKey(i)==='ewa').length;$('count-bom').textContent=zone.filter(i=>U.sourceKey(i)==='bom').length;$('count-wpUnplanned').textContent=zone.filter(i=>U.sourceKey(i)==='wp'&&U.wpCategory(i)==='unplanned').length;$('count-wpPlanned').textContent=zone.filter(i=>U.sourceKey(i)==='wp'&&U.wpCategory(i)==='planned').length;for(const k of ['police','fire','ambulance','hospital','wpFacility']){const n=$(`facility-${k}`),s=A.state.facilities.status[k];if(!n)continue;if(s?.state==='loading')n.textContent='…';else if(s?.state==='error')n.textContent='ERR';else if(s?.state==='ready')n.textContent=A.facilities.visible(k).length;else n.textContent=A.state.settings.layers[k]?'…':'--';}}
function renderWeather(){const d=A.state.weather.perth,c=d?.current,n=$('weatherFreshness');if(!c){$('weatherCondition').textContent=A.state.weather.error?'Weather unavailable':'Loading conditions…';n.textContent='--';return;}$('weatherTemp').textContent=`${Math.round(c.temperature_2m)}°`;$('weatherCondition').textContent=U.weatherLabel(c.weather_code);$('weatherFeels').textContent=`${Math.round(c.apparent_temperature)}°`;$('weatherWind').textContent=`${Math.round(c.wind_speed_10m)} km/h`;$('weatherGust').textContent=`${Math.round(c.wind_gusts_10m)} km/h`;$('weatherRain').textContent=`${Number(c.precipitation||c.rain||0).toFixed(1)} mm`;const f=U.freshness(A.state.weather.updatedAt);n.textContent=f.label;n.className=`freshness-badge ${f.key}`;const daily=d.daily||{},days=daily.time||[];$('forecastStrip').innerHTML=days.map((x,i)=>{const label=i===0?'Today':new Intl.DateTimeFormat('en-AU',{weekday:'short',timeZone:'Australia/Perth'}).format(new Date(`${x}T12:00:00+08:00`));return `<article class="forecast-day"><strong>${label}</strong><span>${U.esc(U.weatherLabel(daily.weather_code?.[i]))}</span><span>${Math.round(daily.temperature_2m_max?.[i])}° / ${Math.round(daily.temperature_2m_min?.[i])}°</span><span>Rain ${Number(daily.precipitation_sum?.[i]||0).toFixed(1)} mm</span></article>`;}).join('');}
function parseFire(xml){try{const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))return[];const rows=[];d.querySelectorAll('area').forEach(a=>{const name=a.getAttribute('description')||a.getAttribute('aac')||'WA district';for(const n of a.querySelectorAll('text,element')){const type=n.getAttribute('type')||n.getAttribute('name')||'',v=(n.textContent||'').trim();if(/fire/i.test(type+v)&&/No Rating|Moderate|High|Extreme|Catastrophic/i.test(v)){rows.push({name,rating:(v.match(/Catastrophic|Extreme|High|Moderate|No Rating/i)||[])[0]||v});break;}}});return rows;}catch{return[];}}
function renderFireDanger(){const s=A.state.fireDanger,d=s.data;if(!d){$('fireDangerStatus').textContent=s.error?'Unavailable':'Loading';$('fireDangerContent').textContent=s.error?'BOM fire-danger feed is unavailable. Use the official BOM forecast to verify current ratings.':'Loading BOM fire-danger information…';return;}const rows=Array.isArray(d.ratings)?d.ratings:parseFire(d.xml||''),order={Catastrophic:5,Extreme:4,High:3,Moderate:2,'No Rating':1};rows.sort((a,b)=>(order[b.rating]||0)-(order[a.rating]||0));$('fireDangerStatus').textContent=d.ok===false?'Last known':'BOM';$('fireDangerContent').innerHTML=rows.length?`Highest loaded rating: <strong>${U.esc(rows[0].rating)}</strong> — ${U.esc(rows[0].name)}. ${rows.length} district rating${rows.length===1?'':'s'} available.`:'Official district feed loaded, but no rating rows were parsed. Verify with BOM.';}
function renderSelected(){const s=A.state.selected,d=A.state.weather.selected,c=d?.current;$('selectedTitle').textContent=s?.label||'No location selected';$('savePlaceBtn').disabled=!s;if(!s){$('selectedCard').innerHTML='<p>Select the map, search for a location or use My location to see local conditions and nearby enabled facilities.</p>';return;}const nearby=A.facilities.nearest({lat:s.lat,lon:s.lon},5);$('selectedCard').innerHTML=`${c?`<div class="selected-weather"><div><span>Temperature</span><b>${Math.round(c.temperature_2m)}°C</b></div><div><span>Conditions</span><b>${U.esc(U.weatherLabel(c.weather_code))}</b></div><div><span>Wind</span><b>${Math.round(c.wind_speed_10m)} km/h</b></div><div><span>Gusts</span><b>${Math.round(c.wind_gusts_10m)} km/h</b></div></div>`:'<p>Local weather is unavailable.</p>'}<h3 style="margin:12px 0 7px;font-size:9px">Nearest enabled facilities</h3><div class="nearby-list">${nearby.length?nearby.map(f=>`<div class="nearby-item"><div><strong>${U.esc(f.name)}</strong><span>${U.esc(A.facilities.META[f.kind]?.label||f.kind)}</span></div><span>${f.distanceKm.toFixed(f.distanceKm<10?1:0)} km</span></div>`).join(''):'<p class="helptext">Enable facility layers to calculate nearby reference locations.</p>'}</div>`;}
function renderSaved(){const items=A.state.settings.savedPlaces||[];$('savedPlaces').innerHTML=items.length?items.map(p=>`<div class="saved-item" data-saved-id="${U.esc(p.id)}"><div><strong>${U.esc(p.label)}</strong><span>${p.lat.toFixed(4)}, ${p.lon.toFixed(4)}</span></div><button type="button" data-remove-saved="${U.esc(p.id)}">Remove</button></div>`).join(''):'<p class="helptext">No saved places yet.</p>';}
function renderSources(){const sources=A.state.feeds.sources||{},rows=[['BOM warnings','bom'],['Emergency WA','emergency'],['Western Power','westernPower'],['Main Roads','mainRoads']],bad=rows.filter(([,k])=>sources[k]?.ok===false).length;$('sourceHealthSummary').textContent=bad?`${bad} issue${bad===1?'':'s'}`:'Feeds healthy';$('sourceList').innerHTML=rows.map(([label,k])=>{const s=sources[k],ok=s?.ok===true,state=ok?'good':s?'bad':'warn',txt=ok?`Live · ${s.count??0} items`:s?.message||'Waiting for feed';return `<div class="source-item"><div><strong>${label}</strong><span>${U.esc(txt)}</span></div><span class="source-state ${state}">${ok?'OK':s?'ERROR':'WAIT'}</span></div>`;}).join('');}
function renderModes(){qa('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===A.state.settings.mode));qa('[data-layer]').forEach(i=>i.checked=!!A.state.settings.layers[i.dataset.layer]);$('zoneSelect').value=A.state.settings.zone;$('basemapSelect').value=A.state.settings.basemap;}
function renderPanels(){qa('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===A.state.settings.panel));qa('.panel-view').forEach(v=>v.classList.toggle('active',v.dataset.view===A.state.settings.panel));}
function renderFilters(){qa('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===incidentFilter));}
function renderNetwork(){const n=$('networkPill');n.textContent=A.state.online?'ONLINE':'OFFLINE';n.className=`status-pill ${A.state.online?'live':'offline'}`;}
function renderAll(){renderMetrics();renderIncidents();renderFreshness();renderLayerCounts();renderWeather();renderFireDanger();renderSelected();renderSaved();renderSources();renderModes();renderPanels();renderFilters();renderNetwork();}
function switchPanel(id){A.setSetting('panel',id);renderPanels();}
function shiftBrief(){const items=allItems(),priority=items.filter(i=>U.scoreItem(i)>=70).sort((a,b)=>U.scoreItem(b)-U.scoreItem(a)),wp=items.filter(i=>U.sourceKey(i)==='wp'&&U.wpCategory(i)==='unplanned'),customers=wp.reduce((n,i)=>n+(Number(i.customersImpacted)||0),0),ewa=items.filter(i=>U.sourceKey(i)==='ewa'),bom=items.filter(i=>U.sourceKey(i)==='bom'),roads=items.filter(i=>U.sourceKey(i)==='mr'&&['closed','incident','signal','detour'].includes(i.category));const top=priority.slice(0,6).map(i=>`- ${sourceLabel(i)}: ${U.itemTitle(i)}${U.itemSubtitle(i)?` — ${U.itemSubtitle(i)}`:''}`).join('\n')||'- No high-priority items in the selected work zone.';return `WAOS shift brief — ${A.ZONES[A.state.settings.zone]?.label||'SWIN'}\nGenerated ${new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Perth',dateStyle:'medium',timeStyle:'short'}).format(new Date())}\n\nOperational picture\nPriority items: ${priority.length}\nWestern Power unplanned: ${wp.length} outages / ${customers.toLocaleString('en-AU')} customers\nEmergency WA: ${ewa.length}\nBOM warnings: ${bom.length}\nKey road impacts: ${roads.length}\n\nAttention now\n${top}\n\nWAOS is a personal situational-awareness tool. Verify safety-critical information with official sources.`;}
async function copyBrief(){try{await navigator.clipboard.writeText(shiftBrief());toast('Shift brief copied.');}catch{toast('Clipboard access was unavailable.');}}
function bind(){setInterval(()=>{$('clock').textContent=U.perthTime();},1000);$('clock').textContent=U.perthTime();$('refreshBtn').onclick=async()=>{toast('Refreshing operational data…');await A.data.refreshAll();await A.facilities.loadEnabled();renderAll();};$('copyBriefBtn').onclick=copyBrief;$('searchForm').onsubmit=async e=>{e.preventDefault();const q=$('searchInput').value.trim();if(!q)return;try{$('searchInput').blur();await A.map.search(q);switchPanel('tools');}catch(err){toast(err.message||'Search failed.');}};$('locateBtn').onclick=async()=>{try{await A.map.locate();switchPanel('tools');}catch(e){toast(e.message||'Location unavailable.');}};$('zoneSelect').onchange=e=>A.map.setZone(e.target.value);$('basemapSelect').onchange=e=>A.map.setBasemap(e.target.value);qa('[data-mode]').forEach(b=>b.onclick=()=>{A.applyMode(b.dataset.mode);renderAll();});qa('[data-panel]').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));qa('[data-filter]').forEach(b=>b.onclick=()=>{incidentFilter=b.dataset.filter;renderFilters();renderIncidents();});qa('[data-layer]').forEach(i=>i.onchange=async()=>{const k=i.dataset.layer;A.setLayer(k,i.checked);if(i.checked&&['police','fire','ambulance','hospital','wpFacility'].includes(k))await A.facilities.load(k);A.map.render();renderAll();});$('clearLayersBtn').onclick=()=>{for(const k of Object.keys(A.state.settings.layers))A.setLayer(k,false);renderAll();A.map.render();};$('savePlaceBtn').onclick=()=>{const s=A.state.selected;if(!s)return;A.addSavedPlace(s);renderSaved();toast('Place saved on this device.');};$('clearSavedBtn').onclick=()=>{A.state.settings.savedPlaces=[];U.saveJSON('settings',A.state.settings);A.emit('savedPlaces',{});renderSaved();};$('incidentList').onclick=e=>{if(e.target.closest('a'))return;const card=e.target.closest('[data-item-id]');if(card)A.map.focusItem(card.dataset.itemId);};$('savedPlaces').onclick=async e=>{const remove=e.target.closest('[data-remove-saved]');if(remove){A.removeSavedPlace(remove.dataset.removeSaved);renderSaved();return;}const row=e.target.closest('[data-saved-id]'),p=A.state.settings.savedPlaces.find(x=>x.id===row?.dataset.savedId);if(p){A.map.map.setView([p.lat,p.lon],14,{animate:true});await A.map.selectPoint(p.lat,p.lon,p.label);}};document.addEventListener('keydown',e=>{if(/input|textarea|select/i.test(document.activeElement?.tagName||''))return;if(e.key==='/'){e.preventDefault();$('searchInput').focus();}if(e.key.toLowerCase()==='r')$('refreshBtn').click();if(e.key.toLowerCase()==='p')A.applyMode('priority');if(e.key==='1')A.applyMode('power');if(e.key==='2')A.applyMode('warnings');if(e.key==='3')A.applyMode('roads');if(e.key==='0')A.applyMode('everything');});}
async function boot(){try{bind();renderModes();renderPanels();A.map.init();renderAll();A.data.start();await Promise.allSettled([A.data.refreshAll(),A.facilities.loadEnabled()]);A.map.render();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){console.error(e);toast(`WAOS could not start: ${e.message||e}`);}}
A.events.addEventListener('feeds',renderAll);A.events.addEventListener('weather',renderWeather);A.events.addEventListener('fireDanger',renderFireDanger);A.events.addEventListener('selection',()=>{renderSelected();renderPanels();});A.events.addEventListener('facilities',()=>{renderLayerCounts();renderSelected();});A.events.addEventListener('settings',renderAll);A.events.addEventListener('layers',()=>{renderModes();renderIncidents();renderFreshness();});A.events.addEventListener('mode',renderAll);A.events.addEventListener('savedPlaces',renderSaved);A.events.addEventListener('network',renderNetwork);A.events.addEventListener('toast',e=>toast(e.detail?.message||''));A.events.addEventListener('refreshing',e=>{$('refreshBtn').textContent=e.detail?.value?'Refreshing…':'Refresh';$('refreshBtn').disabled=!!e.detail?.value;});
boot();
})();