(function(){
'use strict';

const STORAGE_PREFIX='waos4:';
const PERTH={lat:-31.9523,lon:115.8613,label:'Perth'};
const SWIN_RING=[[-27.55,114.05],[-27.45,114.55],[-28.35,115.70],[-29.10,116.25],[-29.80,116.60],[-30.50,117.20],[-30.60,118.50],[-30.80,119.60],[-30.45,121.00],[-30.45,121.75],[-31.40,122.00],[-31.55,120.60],[-31.85,119.40],[-32.45,118.75],[-33.20,120.20],[-33.75,120.10],[-34.10,119.75],[-34.55,119.50],[-35.10,118.35],[-35.15,117.60],[-35.05,116.90],[-34.70,116.20],[-34.35,115.20],[-33.85,114.90],[-33.25,115.10],[-32.60,115.60],[-31.95,115.65],[-31.25,115.40],[-30.55,115.00],[-29.85,114.80],[-29.10,114.85],[-28.35,114.50]];
const ZONES={swin:{label:'SWIN',bounds:[[-35.30,113.90],[-27.20,122.30]]},metro:{label:'Metro',bounds:[[-32.75,115.45],[-31.25,116.35]]},southmetro:{label:'South Metro',bounds:[[-32.75,115.50],[-31.90,116.30]]},northmetro:{label:'North Metro',bounds:[[-31.95,115.45],[-31.25,116.30]]},southcountry:{label:'South Country',bounds:[[-35.30,114.60],[-32.70,120.35]]},northcountry:{label:'North Country',bounds:[[-31.30,113.95],[-27.30,119.25]]},eastcountry:{label:'East Country',bounds:[[-33.30,116.15],[-30.15,122.25]]}};
const COLORS={bom:'#eab308',ewa:'#dc2626',wpUnplanned:'#f97316',wpPlanned:'#16a34a',wpUnknown:'#64748b',mrIncident:'#2563eb',mrSignal:'#db2777',mrRoadworks:'#0891b2',mrEvent:'#7c3aed',mrClosed:'#991b1b',mrRestriction:'#9333ea',mrCondition:'#92400e',mrDetour:'#475569',police:'#2563eb',fire:'#dc2626',ambulance:'#ef4444',hospital:'#ffffff',wpFacility:'#f97316'};
const DEFAULT_LAYERS={bom:true,ewa:true,wpUnplanned:true,wpPlanned:true,mrIncident:true,mrSignal:true,mrRoadworks:false,mrEvent:true,mrClosed:true,mrRestriction:true,mrCondition:false,mrDetour:true,radar:false,police:false,fire:false,ambulance:false,hospital:false,wpFacility:false};
const MODES={priority:{label:'Priority',layers:{bom:true,ewa:true,wpUnplanned:true,wpPlanned:false,mrIncident:true,mrSignal:true,mrRoadworks:false,mrEvent:false,mrClosed:true,mrRestriction:false,mrCondition:false,mrDetour:true}},power:{label:'Power',layers:{bom:false,ewa:false,wpUnplanned:true,wpPlanned:true,mrIncident:false,mrSignal:false,mrRoadworks:false,mrEvent:false,mrClosed:false,mrRestriction:false,mrCondition:false,mrDetour:false}},warnings:{label:'Warnings',layers:{bom:true,ewa:true,wpUnplanned:false,wpPlanned:false,mrIncident:false,mrSignal:false,mrRoadworks:false,mrEvent:false,mrClosed:false,mrRestriction:false,mrCondition:false,mrDetour:false}},roads:{label:'Roads',layers:{bom:false,ewa:false,wpUnplanned:false,wpPlanned:false,mrIncident:true,mrSignal:true,mrRoadworks:true,mrEvent:true,mrClosed:true,mrRestriction:true,mrCondition:true,mrDetour:true}},everything:{label:'Everything',layers:{bom:true,ewa:true,wpUnplanned:true,wpPlanned:true,mrIncident:true,mrSignal:true,mrRoadworks:true,mrEvent:true,mrClosed:true,mrRestriction:true,mrCondition:true,mrDetour:true}}};
const WEATHER_CODES={0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Fog',48:'Fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm with hail',99:'Severe thunderstorm'};
function clone(v){return JSON.parse(JSON.stringify(v));}
function loadJSON(key,fallback){try{const raw=localStorage.getItem(STORAGE_PREFIX+key);return raw?JSON.parse(raw):clone(fallback);}catch{return clone(fallback);}}
function saveJSON(key,value){try{localStorage.setItem(STORAGE_PREFIX+key,JSON.stringify(value));}catch{}}
function esc(value=''){return String(value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmtTime(value,withDate=true){if(!value)return 'Not supplied';const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Perth',day:withDate?'numeric':undefined,month:withDate?'short':undefined,hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
function perthTime(){return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Perth',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date());}
function weatherLabel(code){return WEATHER_CODES[code]||'Conditions';}
function ageMinutes(value){const t=new Date(value||0).getTime();return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):Infinity;}
function freshness(value){const m=ageMinutes(value);if(m<10)return {key:'live',label:'LIVE',minutes:m};if(m<30)return {key:'delayed',label:'DELAYED',minutes:m};if(Number.isFinite(m))return {key:'stale',label:'STALE',minutes:m};return {key:'unknown',label:'UNKNOWN',minutes:m};}
function inBounds(lat,lon,bounds){return lat>=bounds[0][0]&&lat<=bounds[1][0]&&lon>=bounds[0][1]&&lon<=bounds[1][1];}
function inSwin(lat,lon){let inside=false;for(let i=0,j=SWIN_RING.length-1;i<SWIN_RING.length;j=i++){const yi=SWIN_RING[i][0],xi=SWIN_RING[i][1],yj=SWIN_RING[j][0],xj=SWIN_RING[j][1];if(((yi>lat)!==(yj>lat))&&(lon<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi))inside=!inside;}return inside;}
function pointInZone(lat,lon,id){const z=ZONES[id]||ZONES.swin;return inBounds(lat,lon,z.bounds)&&inSwin(lat,lon);}
function haversine(a,b){const R=6371,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lon-a.lon),p=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(p),Math.sqrt(1-p));}
function geometryCenter(g){if(!g)return null;const coords=[];const walk=v=>{if(Array.isArray(v)&&v.length>=2&&Number.isFinite(+v[0])&&Number.isFinite(+v[1])&&typeof v[0]!=='object'){coords.push([+v[1],+v[0]]);return;}if(Array.isArray(v))v.forEach(walk);};walk(g.coordinates);if(!coords.length)return null;const s=coords.reduce((a,p)=>[a[0]+p[0],a[1]+p[1]],[0,0]);return {lat:s[0]/coords.length,lon:s[1]/coords.length};}
function itemPoint(item){if(Array.isArray(item?.point)&&item.point.length>=2)return {lat:+item.point[0],lon:+item.point[1]};return geometryCenter(item?.geometry)||null;}
function sourceKey(item){const s=String(item?.source||'').toLowerCase();if(s.includes('western power'))return 'wp';if(s.includes('emergency'))return 'ewa';if(s.includes('main roads'))return 'mr';return 'bom';}
function wpCategory(item){if(item?.outageCategory)return item.outageCategory;if(item?.planned===true)return 'planned';if(item?.planned===false)return 'unplanned';return 'unknown';}
function roadLayerKey(category){return ({incident:'mrIncident',signal:'mrSignal',roadworks:'mrRoadworks',event:'mrEvent',closed:'mrClosed',restriction:'mrRestriction',condition:'mrCondition',detour:'mrDetour'})[category]||'mrIncident';}
function itemLayerKey(item){const src=sourceKey(item);if(src==='wp')return wpCategory(item)==='planned'?'wpPlanned':'wpUnplanned';if(src==='mr')return roadLayerKey(item.category);return src==='ewa'?'ewa':'bom';}
function itemId(item){return `${sourceKey(item)}:${String(item?.id||item?.rawId||item?.title||Math.random())}`;}
function scoreItem(item){const src=sourceKey(item);let score=0;if(src==='ewa')score=95;else if(src==='wp'){const cat=wpCategory(item);score=cat==='unplanned'?80:30;const customers=Number(item.customersImpacted||0);score+=Math.min(18,Math.log10(Math.max(1,customers))*5);}else if(src==='bom'){score=65;const sev=String(item.severity||item.title||'').toLowerCase();if(/emergency|extreme|catastrophic/.test(sev))score+=25;else if(/severe|warning/.test(sev))score+=12;}else if(src==='mr'){score=({closed:75,incident:68,signal:60,detour:55,restriction:48,event:35,condition:30,roadworks:20})[item.category]||30;}return Math.round(score);}
function itemTitle(item){const src=sourceKey(item);if(src==='wp')return item.affectedArea||item.title||'Western Power outage';return item.title||item.categoryLabel||'Operational item';}
function itemSubtitle(item){const src=sourceKey(item);if(src==='wp'){const c=item.customersImpacted!=null?`${Number(item.customersImpacted).toLocaleString('en-AU')} customers`:'Customer count unavailable';const t=item.estimatedRestorationTime?`ETR ${fmtTime(item.estimatedRestorationTime)}`:'No restoration estimate';return `${c} · ${t}`;}if(src==='mr')return [item.road,item.suburb,item.trafficImpact].filter(Boolean).join(' · ');return [item.area,item.severity].filter(Boolean).join(' · ');}
function visibleForZone(item,zoneId){const p=itemPoint(item);return !p||pointInZone(p.lat,p.lon,zoneId);}
function debounce(fn,ms=180){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms);};}
const events=new EventTarget();
const settings=loadJSON('settings',{zone:'swin',mode:'priority',layers:DEFAULT_LAYERS,basemap:'street',panel:'incidents',savedPlaces:[]});settings.layers={...DEFAULT_LAYERS,...(settings.layers||{})};if(!ZONES[settings.zone])settings.zone='swin';if(!MODES[settings.mode])settings.mode='priority';
const state={settings,feeds:{bom:[],emergency:[],westernPower:[],mainRoads:[],sources:{},updatedAt:null,usingCache:false,error:null},weather:{perth:null,selected:null,updatedAt:null,error:null},fireDanger:{data:null,updatedAt:null,error:null},outageHistory:{data:null,updatedAt:null,error:null},facilities:{police:[],fire:[],ambulance:[],hospital:[],wpFacility:[],status:{}},selected:null,refreshing:false,online:navigator.onLine};
function emit(name,detail){events.dispatchEvent(new CustomEvent(name,{detail}));}
function setSetting(key,value){state.settings[key]=value;saveJSON('settings',state.settings);emit('settings',{key,value});}
function setLayer(key,value){state.settings.layers[key]=!!value;saveJSON('settings',state.settings);emit('layers',{key,value:!!value});}
function applyMode(id){if(!MODES[id])return;state.settings.mode=id;state.settings.layers={...state.settings.layers,...MODES[id].layers};saveJSON('settings',state.settings);emit('mode',{id});emit('layers',{mode:id});}
function addSavedPlace(place){const p={id:place.id||`p-${Date.now()}`,label:place.label||'Saved place',lat:+place.lat,lon:+place.lon};state.settings.savedPlaces=[p,...state.settings.savedPlaces.filter(x=>x.id!==p.id)].slice(0,12);saveJSON('settings',state.settings);emit('savedPlaces',{});return p;}
function removeSavedPlace(id){state.settings.savedPlaces=state.settings.savedPlaces.filter(x=>x.id!==id);saveJSON('settings',state.settings);emit('savedPlaces',{});}
window.WAOS4={version:'4.0.0',PERTH,SWIN_RING,ZONES,COLORS,DEFAULT_LAYERS,MODES,state,events,emit,setSetting,setLayer,applyMode,addSavedPlace,removeSavedPlace,utils:{clone,loadJSON,saveJSON,esc,fmtTime,perthTime,weatherLabel,ageMinutes,freshness,inBounds,inSwin,pointInZone,haversine,geometryCenter,itemPoint,sourceKey,wpCategory,roadLayerKey,itemLayerKey,itemId,scoreItem,itemTitle,itemSubtitle,visibleForZone,debounce}};
})();