(function(){
'use strict';
const A=window.WAOS4,U=A.utils;
const CACHE_PREFIX='facility:';
const TTL={fire:7*24*60*60*1000,hospital:7*24*60*60*1000,police:24*60*60*1000,ambulance:24*60*60*1000,wpFacility:30*24*60*60*1000};
const DFES_URL='https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Infrastructure_and_Utilities/MapServer/33/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson';
const HEALTH_URL='https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Health/MapServer/7/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=geojson';
const OVERPASS=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const WP_PUBLIC=[{name:'South Metro Depot / Boyli Mia',query:'Western Power South Metro Depot, Forrestdale WA',note:'Publicly documented Western Power depot'},{name:'Vasse Depot / Mulgarup / Balbarignup',query:'Western Power Vasse Depot, 19 Ostler Drive, Vasse WA 6280',note:'Publicly mapped/documented Western Power depot'},{name:'Pinjarra Depot',query:'Western Power Pinjarra Depot, Pinjarra WA',note:'Publicly documented Western Power depot'},{name:'Albany Depot / Kinjarling Pindjarri',query:'Western Power Albany Depot, Albany WA',note:'Publicly documented Western Power depot'},{name:'Picton Depot',query:'Western Power Picton Depot, 1757 Boyanup-Picton Road, Picton WA 6229',note:'Publicly documented Western Power depot'},{name:'Northam Depot',query:'Western Power Depot, Northam WA',note:'Publicly documented operational location'},{name:'Narrogin Depot',query:'Western Power Depot, Narrogin WA',note:'Publicly documented operational location'},{name:'Merredin Depot',query:'Western Power Depot, Merredin WA',note:'Publicly documented operational location'},{name:'Geraldton Depot',query:'Western Power Depot, Geraldton WA',note:'Publicly documented operational location'},{name:'Three Springs Depot',query:'Western Power Depot, Three Springs WA',note:'Publicly documented operational location'}];
const META={police:{label:'Police',source:'OpenStreetMap mapped police facilities; verify with WA Police',verify:'https://www.police.wa.gov.au/'},fire:{label:'Fire / DFES',source:'WA Government DFES Stations (DFES-023)',verify:'https://catalogue.data.wa.gov.au/dataset/dfes-stations'},ambulance:{label:'Ambulance',source:'OpenStreetMap mapped ambulance facilities; verify with St John WA',verify:'https://www.stjohnwa.com.au/ambulance-and-health-services/'},hospital:{label:'Emergency hospital',source:'WA Health Hospitals (HEALTH-001), emergency-department reporting',verify:'https://catalogue.data.wa.gov.au/dataset/health-establishments'},wpFacility:{label:'Western Power facility',source:'Publicly documented Western Power depot/operational locations',verify:'https://www.westernpower.com.au/'}};
let inFlight={};
function cacheKey(kind,zone='all'){return `${CACHE_PREFIX}${kind}:${zone}`;}
function getCache(kind,zone='all'){const c=U.loadJSON(cacheKey(kind,zone),null);return c?.savedAt&&Date.now()-c.savedAt<(TTL[kind]||86400000)&&Array.isArray(c.items)?c.items:null;}
function putCache(kind,items,zone='all'){U.saveJSON(cacheKey(kind,zone),{savedAt:Date.now(),items});return items;}
function status(kind,state,message='',count=null){A.state.facilities.status[kind]={state,message,count,updatedAt:new Date().toISOString()};A.emit('facilities',{kind,state,message,count});}
function prop(a,names){for(const n of names){if(a?.[n]!=null&&String(a[n]).trim()!=='')return a[n];}return '';}
function featurePoint(f){const c=f?.geometry?.coordinates;if(f?.geometry?.type==='Point'&&Array.isArray(c)&&Number.isFinite(+c[0])&&Number.isFinite(+c[1]))return {lat:+c[1],lon:+c[0]};return U.geometryCenter(f?.geometry);}
function addressFromProps(a){return [prop(a,['address','ADDRESS','street_address','StreetAddress']),prop(a,['suburb','SUBURB','locality','LOCALITY']),prop(a,['postcode','POSTCODE'])].filter(Boolean).join(', ');}
function fireTypeOk(v){const s=String(v||'').toUpperCase();return ['BFB','CFRS','PFRS','VFESU','VFRS'].includes(s)||/FIRE|BRIGADE|RESCUE/.test(s);}
async function official(kind,url){const cached=getCache(kind);if(cached)return cached;status(kind,'loading','Loading official WA Government data');const r=await A.data.request(url,{timeout:24000,retries:1});const d=await r.json();const features=Array.isArray(d?.features)?d.features:[];const items=[];for(const f of features){const p=featurePoint(f),a=f.properties||{};if(!p||!U.inSwin(p.lat,p.lon))continue;if(kind==='fire'){const type=prop(a,['type','TYPE','station_ty','station_type','featuretyp']);if(!fireTypeOk(type))continue;items.push({id:`fire-${prop(a,['objectid','OBJECTID','id'])||items.length}`,kind,name:prop(a,['displaynam','DISPLAYNAM','name','NAME','station_name'])||'DFES station',subtype:String(type||'Fire station'),lat:p.lat,lon:p.lon,address:addressFromProps(a),source:META.fire.source,verify:META.fire.verify});}else{const keys=Object.keys(a);const edKey=keys.find(k=>/emergency.*department.*report|ed_report/i.test(k));const ed=edKey?a[edKey]:prop(a,['emergency_department','EmergencyDepartment','ED']);const s=String(ed??'').trim().toLowerCase();const yes=['yes','y','true','1','ed'].includes(s)||/emergency department/.test(s);if(!yes)continue;items.push({id:`hospital-${prop(a,['objectid','OBJECTID','estab_id','ESTAB_ID'])||items.length}`,kind,name:prop(a,['establishm','ESTABLISHM','name','NAME','facility_name'])||'Hospital',subtype:'Emergency department',lat:p.lat,lon:p.lon,address:addressFromProps(a),phone:prop(a,['telephone','TELEPHONE','phone','PHONE']),source:META.hospital.source,verify:META.hospital.verify});}}putCache(kind,items);status(kind,'ready','Official data loaded',items.length);return items;}
function zoneBoxes(zoneId){if(zoneId!=='swin'){const b=A.ZONES[zoneId]?.bounds||A.ZONES.swin.bounds;return [[b[0][0],b[0][1],b[1][0],b[1][1]]];}return [[-35.30,114.00,-32.55,119.00],[-32.65,114.00,-30.70,118.60],[-31.30,113.95,-27.20,119.25],[-33.50,118.45,-30.10,122.30]];}
function overpassClause(kind,bb){const box=bb.join(',');if(kind==='police')return `nwr["amenity"="police"](${box});`;return `nwr["emergency"="ambulance_station"](${box});nwr["amenity"="ambulance_station"](${box});`;}
async function overpassBox(kind,bb){const q=`[out:json][timeout:18];(${overpassClause(kind,bb)});out center tags;`;let last;for(const base of OVERPASS){try{const r=await A.data.request(base,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),timeout:22000,retries:0});const d=await r.json();return Array.isArray(d?.elements)?d.elements:[];}catch(e){last=e;}}throw last||new Error('Mapped facility service unavailable');}
function osmPoint(e){const lat=Number(e?.lat??e?.center?.lat),lon=Number(e?.lon??e?.center?.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:null;}
function osmAddress(t={}){return [[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' '),t['addr:suburb']||t['addr:city']||t['addr:town'],t['addr:postcode']].filter(Boolean).join(', ');}
async function osm(kind,zoneId){const cached=getCache(kind,zoneId);if(cached)return cached;status(kind,'loading',`Loading ${META[kind].label.toLowerCase()} for ${A.ZONES[zoneId]?.label||'SWIN'}`);const boxes=zoneBoxes(zoneId),settled=await Promise.allSettled(boxes.map(b=>overpassBox(kind,b)));const ok=settled.filter(x=>x.status==='fulfilled');if(!ok.length)throw settled[0]?.reason||new Error('Mapped facility service unavailable');const seen=new Set(),items=[];for(const s of ok){for(const e of s.value){const p=osmPoint(e),t=e.tags||{};if(!p||!U.inSwin(p.lat,p.lon)||!U.pointInZone(p.lat,p.lon,zoneId))continue;const key=`${e.type}-${e.id}`;if(seen.has(key))continue;seen.add(key);items.push({id:`${kind}-${key}`,kind,name:t.name||META[kind].label,subtype:t.operator||META[kind].label,lat:p.lat,lon:p.lon,address:osmAddress(t),phone:t.phone||'',source:META[kind].source,verify:META[kind].verify});}}putCache(kind,items,zoneId);status(kind,'ready',ok.length<boxes.length?'Loaded with partial mapped-source coverage':'Mapped data loaded',items.length);return items;}
async function nominatim(q){const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=au&q=${encodeURIComponent(q)}`;const r=await A.data.request(url,{timeout:14000,retries:0,headers:{'Accept':'application/json'}});const d=await r.json();const x=Array.isArray(d)?d[0]:null;if(!x)return null;const lat=+x.lat,lon=+x.lon;return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon,display:x.display_name||''}:null;}
async function westernPower(){const cached=getCache('wpFacility');if(cached)return cached;status('wpFacility','loading','Resolving publicly documented Western Power locations');const items=[];for(const site of WP_PUBLIC){try{const p=await nominatim(site.query);if(p&&U.inSwin(p.lat,p.lon)){items.push({id:`wp-${items.length}-${site.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,kind:'wpFacility',name:site.name,subtype:site.note,lat:p.lat,lon:p.lon,address:p.display,source:META.wpFacility.source,verify:META.wpFacility.verify});}await new Promise(r=>setTimeout(r,1050));}catch{await new Promise(r=>setTimeout(r,1050));}}if(!items.length)throw new Error('Could not resolve public Western Power locations');putCache('wpFacility',items);status('wpFacility','ready','Public locations loaded',items.length);return items;}
async function load(kind,{force=false}={}){const zone=A.state.settings.zone;if(!force&&inFlight[kind])return inFlight[kind];inFlight[kind]=(async()=>{try{let items;if(kind==='fire')items=await official('fire',DFES_URL);else if(kind==='hospital')items=await official('hospital',HEALTH_URL);else if(kind==='police'||kind==='ambulance')items=await osm(kind,zone);else if(kind==='wpFacility')items=await westernPower();else items=[];A.state.facilities[kind]=items;status(kind,'ready','Facility data ready',items.length);return items;}catch(e){status(kind,'error',String(e?.message||e),null);return A.state.facilities[kind]||[];}finally{delete inFlight[kind];}})();return inFlight[kind];}
async function loadEnabled(){const enabled=['police','fire','ambulance','hospital','wpFacility'].filter(k=>A.state.settings.layers[k]);return Promise.allSettled(enabled.map(k=>load(k)));}
function visible(kind,zoneId=A.state.settings.zone){return (A.state.facilities[kind]||[]).filter(x=>U.pointInZone(x.lat,x.lon,zoneId));}
function allVisible(zoneId=A.state.settings.zone){return ['police','fire','ambulance','hospital','wpFacility'].flatMap(k=>A.state.settings.layers[k]?visible(k,zoneId):[]);}
function nearest(point,limit=5){return allVisible().map(x=>({...x,distanceKm:U.haversine(point,{lat:x.lat,lon:x.lon})})).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,limit);}
A.events.addEventListener('settings',e=>{if(e.detail?.key==='zone'){for(const k of ['police','ambulance'])if(A.state.settings.layers[k])load(k,{force:true});}});
A.facilities={META,load,loadEnabled,visible,allVisible,nearest};
})();