(function(){
'use strict';
const A=window.WAOS4,U=A.utils,C=A.COLORS;
let map=null,selectedMarker=null,radarLayer=null,radarMetaAt=0;
const groups={},itemIndex=new Map();
const BASES={};
const layerKeys=['bom','ewa','wpUnplanned','wpPlanned','mrIncident','mrSignal','mrRoadworks','mrEvent','mrClosed','mrRestriction','mrCondition','mrDetour','police','fire','ambulance','hospital','wpFacility'];
const roadColours={incident:C.mrIncident,signal:C.mrSignal,roadworks:C.mrRoadworks,event:C.mrEvent,closed:C.mrClosed,restriction:C.mrRestriction,condition:C.mrCondition,detour:C.mrDetour};
function popupLink(url,label='Official source'){return url?`<a href="${U.esc(url)}" target="_blank" rel="noopener">${U.esc(label)}</a>`:'';}
function itemPopup(i){const src=U.sourceKey(i),title=U.itemTitle(i),sub=U.itemSubtitle(i);let meta='';let link=i.link||'';if(src==='wp'){meta=`${U.wpCategory(i).toUpperCase()}${i.incidentRef?` · Incident ${U.esc(i.incidentRef)}`:''}`;link=link||'https://www.westernpower.com.au/faults-outages/power-outages/';}else if(src==='mr')meta=`Main Roads WA · ${U.esc(i.categoryLabel||i.category||'Road item')}`;else meta=src==='ewa'?'Emergency WA':'BOM';return `<div class="map-popup"><strong>${U.esc(title)}</strong>${sub?`<span>${U.esc(sub)}</span>`:''}<small>${meta}</small>${popupLink(link)}</div>`;}
function facilityPopup(f){return `<div class="map-popup"><strong>${U.esc(f.name)}</strong><span>${U.esc(f.subtype||A.facilities.META[f.kind]?.label||'Facility')}</span>${f.address?`<small>${U.esc(f.address)}</small>`:''}${f.phone?`<small>${U.esc(f.phone)}</small>`:''}<small>${U.esc(f.source||'Reference location')}</small>${popupLink(f.verify,'Verify source')}</div>`;}
function init(){if(typeof L==='undefined')throw new Error('Leaflet failed to load');map=L.map('map',{zoomControl:false,preferCanvas:true,minZoom:5,maxZoom:19,worldCopyJump:false}).setView([A.PERTH.lat,A.PERTH.lon],9);L.control.zoom({position:'bottomright'}).addTo(map);BASES.street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});BASES.satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Esri'});BASES.topo=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap contributors'});(BASES[A.state.settings.basemap]||BASES.street).addTo(map);for(const k of layerKeys)groups[k]=L.layerGroup();drawBoundary();syncLayerVisibility();map.on('click',e=>selectPoint(e.latlng.lat,e.latlng.lng,`${e.latlng.lat.toFixed(4)}, ${e.latlng.lng.toFixed(4)}`));map.on('moveend',()=>A.emit('mapmove',{center:map.getCenter(),zoom:map.getZoom()}));fitZone(A.state.settings.zone,false);A.emit('mapready',{});}
function drawBoundary(){const ring=A.SWIN_RING.map(p=>[p[0],p[1]]),outer=[[-90,-180],[-90,180],[90,180],[90,-180]];L.polygon([outer,ring],{stroke:false,fillColor:'#020406',fillOpacity:.58,fillRule:'evenodd',interactive:false}).addTo(map);L.polyline([...ring,ring[0]],{color:'#f97316',weight:2,opacity:.85,dashArray:'7 6',interactive:false}).addTo(map).bindTooltip('Western Power SWIN operational footprint — indicative');}
function clearOperational(){for(const k of layerKeys)groups[k].clearLayers();itemIndex.clear();}
function syncLayerVisibility(){if(!map)return;for(const k of layerKeys){const should=!!A.state.settings.layers[k];const has=map.hasLayer(groups[k]);if(should&&!has)groups[k].addTo(map);if(!should&&has)map.removeLayer(groups[k]);}syncRadar();}
function geometryLayer(geometry,style){if(!geometry)return null;try{return L.geoJSON({type:'Feature',properties:{},geometry},{style:()=>style,pointToLayer:(_,ll)=>L.circleMarker(ll,{radius:7,...style})});}catch{return null;}}
function register(i,layer,popup){itemIndex.set(U.itemId(i),{layer,popup});}
function plotWarnings(){for(const i of [...A.state.feeds.bom,...A.state.feeds.emergency]){if(!U.visibleForZone(i,A.state.settings.zone))continue;const src=U.sourceKey(i),key=src==='ewa'?'ewa':'bom',colour=src==='ewa'?C.ewa:C.bom,popup=itemPopup(i),parts=[];if(Array.isArray(i.point)&&i.point.length>=2){const lat=+i.point[0],lon=+i.point[1];if(Number.isFinite(lat)&&Number.isFinite(lon)){const m=L.circleMarker([lat,lon],{radius:8,color:'#fff',weight:2,fillColor:colour,fillOpacity:1}).bindPopup(popup).addTo(groups[key]);parts.push(m);}}const polygons=Array.isArray(i.polygons)&&i.polygons.length?i.polygons:(Array.isArray(i.polygon)?[i.polygon]:[]);for(const polygon of polygons){const pts=(Array.isArray(polygon)?polygon:[]).filter(p=>Array.isArray(p)&&p.length>=2).map(p=>[+p[0],+p[1]]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1]));if(pts.length>=3){const p=L.polygon(pts,{color:colour,weight:2,fillColor:colour,fillOpacity:.16}).bindPopup(popup).addTo(groups[key]);parts.push(p);}}if(parts.length)register(i,L.featureGroup(parts),popup);}}
function plotPower(){for(const i of A.state.feeds.westernPower){if(!i.geometry||!U.visibleForZone(i,A.state.settings.zone))continue;const cat=U.wpCategory(i),key=cat==='planned'?'wpPlanned':'wpUnplanned',colour=cat==='planned'?C.wpPlanned:C.wpUnplanned,popup=itemPopup(i),g=geometryLayer(i.geometry,{color:colour,weight:2,opacity:.95,fillColor:colour,fillOpacity:.2});if(g){g.bindPopup(popup).addTo(groups[key]);register(i,g,popup);}}}
function plotRoads(){for(const i of A.state.feeds.mainRoads){if(!i.geometry||!U.visibleForZone(i,A.state.settings.zone))continue;const key=U.roadLayerKey(i.category),colour=roadColours[i.category]||C.mrIncident;if(i.category==='roadworks'&&i.geometry?.type==='Point')continue;const popup=itemPopup(i),g=geometryLayer(i.geometry,{color:colour,weight:i.category==='closed'?4:3,opacity:.9,fillColor:colour,fillOpacity:.15});if(g){g.bindPopup(popup).addTo(groups[key]);register(i,g,popup);}}}
function facilityMarker(f){const letter=({police:'P',fire:'F',ambulance:'A',hospital:'H',wpFacility:'WP'})[f.kind]||'•',colour=({police:C.police,fire:C.fire,ambulance:C.ambulance,hospital:C.hospital,wpFacility:C.wpFacility})[f.kind]||'#64748b';const icon=L.divIcon({className:'facility-div-icon',html:`<span class="facility-map-pin facility-${f.kind}" style="--pin:${colour}">${letter}</span>`,iconSize:[28,28],iconAnchor:[14,14]});return L.marker([f.lat,f.lon],{icon,title:f.name,keyboard:true}).bindPopup(facilityPopup(f));}
function plotFacilities(){for(const kind of ['police','fire','ambulance','hospital','wpFacility'])for(const f of A.facilities.visible(kind))facilityMarker(f).addTo(groups[kind]);}
function render(){if(!map)return;clearOperational();plotWarnings();plotPower();plotRoads();plotFacilities();syncLayerVisibility();A.emit('maprendered',{items:itemIndex.size});}
function fitZone(id,animate=true){if(!map)return;const z=A.ZONES[id]||A.ZONES.swin;map.fitBounds(z.bounds,{padding:[24,24],animate,maxZoom:id==='swin'?7:id.includes('metro')||id==='metro'?11:8});}
function setZone(id){if(!A.ZONES[id])return;A.setSetting('zone',id);fitZone(id);render();}
function setBasemap(id){if(!BASES[id]||!map)return;for(const b of Object.values(BASES))if(map.hasLayer(b))map.removeLayer(b);BASES[id].addTo(map);A.setSetting('basemap',id);}
async function selectPoint(lat,lon,label){if(!U.inSwin(lat,lon)){A.emit('toast',{message:'That point is outside the indicative SWIN footprint.'});return;}if(selectedMarker)selectedMarker.remove();selectedMarker=L.marker([lat,lon],{zIndexOffset:1000}).addTo(map).bindPopup('<strong>Selected location</strong><br>Loading conditions…').openPopup();await A.data.loadSelectedWeather(lat,lon,label);const c=A.state.weather.selected?.current;if(c)selectedMarker.setPopupContent(`<strong>${U.esc(label)}</strong><br>${Math.round(c.temperature_2m)}°C · ${U.esc(U.weatherLabel(c.weather_code))}<br>Wind ${Math.round(c.wind_speed_10m)} km/h`).openPopup();}
async function search(query){const q=String(query||'').trim();if(!q)return null;const bounds=A.ZONES.swin.bounds,viewbox=`${bounds[0][1]},${bounds[1][0]},${bounds[1][1]},${bounds[0][0]}`;const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=6&countrycodes=au&bounded=1&viewbox=${encodeURIComponent(viewbox)}&q=${encodeURIComponent(q+', Western Australia')}`;const r=await A.data.request(url,{timeout:14000,retries:1,headers:{Accept:'application/json'}}),d=await r.json(),x=(Array.isArray(d)?d:[]).map(v=>({...v,lat:+v.lat,lon:+v.lon})).find(v=>Number.isFinite(v.lat)&&Number.isFinite(v.lon)&&U.inSwin(v.lat,v.lon));if(!x)throw new Error('No matching place found inside the SWIN');map.setView([x.lat,x.lon],14,{animate:true});await selectPoint(x.lat,x.lon,x.display_name||q);return x;}
function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(new Error('Location is not available on this device'));return;}navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;if(!U.inSwin(lat,lon)){reject(new Error('Your location is outside the indicative SWIN footprint'));return;}map.setView([lat,lon],14,{animate:true});await selectPoint(lat,lon,'Your location');resolve({lat,lon});},()=>reject(new Error('Location permission was not available')),{enableHighAccuracy:false,timeout:12000,maximumAge:300000});});}
function focusItem(id){const x=itemIndex.get(id);if(!x)return false;try{const b=x.layer.getBounds?.();if(b?.isValid?.())map.fitBounds(b,{padding:[50,50],maxZoom:14,animate:true});else{const ll=x.layer.getLatLng?.();if(ll)map.setView(ll,14,{animate:true});}setTimeout(()=>{try{x.layer.openPopup?.();}catch{}},280);return true;}catch{return false;}}
async function radarMeta(){if(Date.now()-radarMetaAt<4*60*1000&&window.__waosRadarMeta)return window.__waosRadarMeta;const r=await A.data.request('https://api.rainviewer.com/public/weather-maps.json',{timeout:12000,retries:0});const d=await r.json();window.__waosRadarMeta=d;radarMetaAt=Date.now();return d;}
async function syncRadar(){if(!map)return;if(!A.state.settings.layers.radar){if(radarLayer&&map.hasLayer(radarLayer))map.removeLayer(radarLayer);return;}try{const d=await radarMeta(),frames=d?.radar?.past||[],frame=frames[frames.length-1];if(!frame?.path)return;if(radarLayer)map.removeLayer(radarLayer);radarLayer=L.tileLayer(`https://tilecache.rainviewer.com${frame.path}/256/{z}/{x}/{y}/2/1_1.png`,{opacity:.62,zIndex:350,attribution:'RainViewer'}).addTo(map);}catch{A.emit('toast',{message:'Weather radar is temporarily unavailable.'});}}
A.events.addEventListener('feeds',render);A.events.addEventListener('facilities',render);A.events.addEventListener('layers',syncLayerVisibility);A.events.addEventListener('mode',()=>{syncLayerVisibility();render();});A.events.addEventListener('settings',e=>{if(e.detail?.key==='zone'){fitZone(e.detail.value);render();}});
A.map={init,render,setZone,fitZone,setBasemap,search,locate,selectPoint,focusItem,syncLayerVisibility,get map(){return map;}};
})();